#  _    _ _     _
# | |  | (_)   | |
# | |__| |_  __| | ___
# |  __  | |/ _` |/ _ \
# | |  | | | (_| |  __/
# |_|  |_|_|\__,_|\___|
#
# BrandHider v4.0
# Made by BlowTobacco

# If enabled, the brand will be animated
# If false, only custom-brand will be used
animated-brand: true

# Static brand (used if animated-brand = false)
# Supported: All minecraft legacy colors, &k, &l, &m, &n, &o, &r
# Hex colors WILL NOT work due to Minecraft limitations
custom-brand: '&cBrandHider-4.0'

# This hides the server software in the MOTD / status websites
# Colors are NOT allowed here
motd-version: 'BrandHider-4.0'

# Update period for animation (milliseconds)
# Lower = smoother but more packets
animation-period: 1000

# Animated brand frames
# Uses MiniMessage-like formatting, BUT will be converted
# Hex colors WILL NOT work due to Minecraft limitations
brand-animation:
  - '&4B&crandHider'
  - '&fB&4r&candHider'
  - '&fBr&4a&cndHider'
  - '&fBra&4n&cdHider'
  - '&fBran&4d&cHider'
  - '&fBrand&4H&cider'
  - '&fBrandH&4i&cder'
  - '&fBrandHi&4d&cer'
  - '&fBrandHid&4e&cr'
  - '&fBrandHide&4r'


